### PR TITLE
Capstone-Project

### PR DESCRIPTION
**Pull request by evansnyamekye**
Capstone-PR-Website 🚀 
-I used HTML to build the index.html and about.html page structure.🧇 

I used CSS to style and layout all the web pages contained in this capstone.
Using CSS, I styled the required font, color, size, and spacing of the capstone webpage.
I used Flexbox to properly align items on the webpage 🔗 .
As required by this project, I used javascript to create a dynamic webpage that will display pages directly from javascript files.

### CODE REVIEW

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @evansnyamekye, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No linter errors ✔️ 
- Correct GitHub Flow ✔️ 
- Good implementations ✔️ 
- Descriptive `README` file ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] [`README FILE`]Good job so far! You should make use of `GitHub Pages` to deploy the web pages, and project should be deployed properly, all pages, links, and images work as expected. A link to the deployed project is present in the `README` 🙏🏼 

#

- [ ] [REQUIRED] [`HOME PAGE`] Good job so far! Please give correct `position`(e.g center) to card's `heading text` and give correct `hover` effect to each card like a [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 🙏🏼

image

#

- [ ] [REQUIRED] [`HOME PAGE`] Good job so far! Please add any space to `down` and `up` parts of footer section and remove the `horizontal` line on the `footer` section 🙏🏼 

image

#

- [ ] [REQUIRED] [`ABOUT PAGE`] Good job so far! Please add `border` to logo also add the `horizontal` line to required part mentioned  below the picture 🙏🏼  

image

#

- [ ] [REQUIRED] [`ABOUT PAGE`] Good job so far! Please give correct postion and font size to `text` placed on `footer` section 🙏🏼 

image

#

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by evansnyamekye** [comment]
This is already approved work from last week. I only created a new branch
and submitted it.

**Review by nahnahdev — APPROVED** [review]
## Project Status: APPROVED :green_circle: 
Hi @evansnyamekye , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- All requested changes implemented ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mckent05 — COMMENTED** [review]
Hi @evansnyamekye, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
approved


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Your project looks good 👍 👍 

## Optional suggestions
- According to the project requirements, please add the live online version of your project to your readme. This would help make your repo look even more professional 👍 👍

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
